tools/sidekick/config.json
tools/sidekick/library.html

Fix #1
Test URLs:
- After: https://config-setup--walgreens--hlxsites.hlx.page/

Add block library config

---

styles/styles.css

Test URLs:
- Before: https://main--walgreens--hlxsites.hlx.live/personal-care-deals
- After: https://text-color--walgreens--hlxsites.hlx.live/personal-care-deals

chore: Text color

---

blocks/cards/cards.css
blocks/cards/cards.js
styles/styles.css

Fix #13
Test URLs:
- Before: https://main--walgreens--hlxsites.hlx.live/beautydeals
- After: https://cards--walgreens--hlxsites.hlx.live/beautydeals
- Before: https://main--walgreens--hlxsites.hlx.live/personal-care-deals
- After: https://cards--walgreens--hlxsites.hlx.live/personal-care-deals

13 - Cards Block

---

blocks/columns/columns.css
blocks/columns/columns.js

Fix #16
Test URLs:
- Before: https://main--walgreens--hlxsites.hlx.page/drafts/laith/dotw
- After: https://columns-block--walgreens--hlxsites.hlx.page/drafts/laith/dotw

Columns block

---

blocks/hero/hero.css

Fix #7
Test URLs:
- Before: https://main--walgreens--hlxsites.hlx.page/drafts/laith/hero
- After: https://hero-block--walgreens--hlxsites.hlx.page/drafts/laith/hero

#7 hero block

---

blocks/header/header.js
scripts/scripts.js

Fix #5 
Test URLs:
- Before: https://main--walgreens--hlxsites.hlx.live/drafts/rusher/header-api
- After: https://header-api--walgreens--hlxsites.hlx.live/drafts/rusher/header-api

Header api

---

blocks/footer/footer.js
scripts/scripts.js

Fix #6
Test URLs:
- After: https://footer-fix--walgreens--hlxsites.hlx.page/

Adjust Footer

---

blocks/footer/footer.css

add css file

---

blocks/columns/columns.css
scripts/scripts.js

Fix #44
Test URLs:
- Before: https://main--walgreens--hlxsites.hlx.live/vitamin1
- After: https://promo-fix--walgreens--hlxsites.hlx.live/vitamin1

add highlighting and correct sizing

---

.github/workflows/external-css-sync.yaml
blocks/cards/cards.css
blocks/cards/cards.js

Fix #59
Test URLs:
- Before: https://main--walgreens--hlxsites.hlx.live/store/catalog/shoplanding
- After: https://cta-card--walgreens--hlxsites.hlx.live/store/catalog/shoplanding?test

Add cta and border variants

---

blocks/hero/hero.css
blocks/hero/hero.js

Fix #7 
Test URLs (see the Save More with Coupons Hero Block):
- Before: https://main--walgreens--hlxsites.hlx.page/topic/promotion/walgreens-online-deals
- After: https://enhance-hero--walgreens--hlxsites.hlx.live/topic/promotion/walgreens-online-deals

feat: Allow Hero Overrides

---

blocks/columns/columns.js

The CTA columns would not display correctly when the text was all in bold.
Test URLs:
- Before: https://main--walgreens--hlxsites.hlx.page/topic/promotion/walgreens-online-deals
- After: https://columns-cta--walgreens--hlxsites.hlx.page/topic/promotion/walgreens-online-deals

fix bold text issue

---

blocks/columns/columns.css
scripts/delayed.js
scripts/scripts.js

Test URLs:
- Before: https://main--walgreens--hlxsites.hlx.page/store/catalog/shoplanding
- After: https://columns-underline--walgreens--hlxsites.hlx.page/store/catalog/shoplanding?test

adjust underline

---

blocks/faq/faq.css
blocks/faq/faq.js
blocks/sidepanel/sidepanel.css

Fix #9 
Test URLs:
- Before: https://main--walgreens--hlxsites.hlx.page/topic/promotion/walgreens-online-deals
- After: https://faq-accordion--walgreens--hlxsites.hlx.page/topic/promotion/walgreens-online-deals?test

9 - FAQ Accordion

---

blocks/sidepanel/sidepanel.css
blocks/sidepanel/sidepanel.js

Fix #17 
Test URLs:
- Before: https://main--walgreens--hlxsites.hlx.live/store/catalog/shoplanding
- After: https://sidepanel-api--walgreens--hlxsites.hlx.live/store/catalog/shoplanding

17 - Store Landing Sidebar - Enable categories from APIs

---

blocks/columns/columns.css
blocks/faq/faq.css
blocks/faq/faq.js
styles/styles.css

Fix #3 
Test URLs:
- Before: https://main--walgreens--hlxsites.hlx.live/beautydeals
- After: https://cleanup-styling--walgreens--hlxsites.hlx.live/beautydeals

Polish Look & Feel

---

head.html

Test URLs:
- After: https://preload-fix--walgreens--hlxsites.hlx.page/

add as to preload

---

scripts/delayed.js

Test URLs:
- Before: https://main--walgreens--hlxsites.hlx.live/
- After: https://onetrust-cookie--walgreens--hlxsites.hlx.live/

add onetrust cookie

---

scripts/scripts.js
styles/styles.css

Fix #70
Test URLs:
- Before: https://main--walgreens--hlxsites.hlx.page/?test
- After: https://enhanced-backToTopBtn--walgreens--hlxsites.hlx.page/?test

#70 update back to top button

---

styles/styles.css

Fix #73
Test URLs:
- After: https://styling-feeback--walgreens--hlxsites.hlx.page/

fixes border radius

---

scripts/scripts.js

Added pushToDataLayer calls for know content impression analytics.
Fix #75
Test URLs:
- Before: https://main--walgreens--hlxsites.hlx.live/beautydeals
- After: https://content-impressions--walgreens--hlxsites.hlx.live/beautydeals

Content Impression Trigger

---

scripts/delayed.js

Fix #4 
Test URLs:
- After: https://disable-launch-prod--walgreens--hlxsites.hlx.page/

Disable Adobe Launch

---

external-topic/blocks/carousel/carousel.js

Test URLs:
- After: https://disable-launch-prod--walgreens--hlxsites.hlx.page/external-topic/

update style classpath

---

external-topic/blocks/footer/footer.js
external-topic/blocks/header/header.js
external-topic/scripts/aem.js

Adjust the path resolution for the header and footer calls to the worker.
Test URLs:
- Before: https://main--walgreens--hlxsites.hlx.page/external-topic/
- After: https://upgrade-framework--walgreens--hlxsites.hlx.page/external-topic/

adjust worker path

---

external-topic/blocks/breadcrumb/breadcrumb.js
external-topic/blocks/cards/cards.js
external-topic/scripts/aem.js

Improve image sizing.
Add aria-hidden to icon.
Test URLs:
- After: https://optimize-images--walgreens--hlxsites.hlx.page/external-topic/topic/promotion/beautydeals

optimize image sizing

---

external-topic/blocks/footer/footer.js
external-topic/scripts/headerfooter-worker.js
external-topic/scripts/scripts.js

Scripts are not loading in the correct order.
Fix #87 
Test URLs:
- After: https://87-scripts-order--walgreens--hlxsites.hlx.page/external-topic/topic/promotion/beautydeals

scripts load order adjustment

---

external-topic/scripts/delayed.js
external-topic/scripts/headerfooter-worker.js
external-topic/scripts/scripts.js

Test URLs:
- After: https://load-order--walgreens--hlxsites.hlx.page/external-topic/topic/promotion/beautydeals

Adjust lsg script load order

---

external-topic/blocks/footer/footer.js
external-topic/blocks/header/header.js
external-topic/scripts/scripts.js

Fix #90 
Test URLs:
- After: https://scripts-load--walgreens--hlxsites.hlx.page/external-topic/topic/promotion/beautydeals

Create nodes for API content scripts

---

external-topic/scripts/scripts.js

Add cookie for v2H=t.
Test URLs:
- After: https://set-cookie--walgreens--hlxsites.hlx.page/external-topic/topic/promotion/beautydeals

set cookie

---

external-topic/scripts/scripts.js

Fix #94 
Test URLs:
- After: https://header-fix--walgreens--hlxsites.hlx.page/external-topic/topic/promotion/beautydeals

Added headerSupport to skip list
